version: "3"
services:
  firefox-standalone:
    image: selenium/standalone-firefox:4.16.1-20231219
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"
    networks:
      - webdriver
networks:
  webdriver:
    external: true
    name: webdriver